import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
<<<<<<< HEAD
    title: "My Eco",
    description: "Eco, eco round bro!",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> parent of 226f003 (chore: update page title)
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
